### ISSUE TITLE
High-DPI icons for server (and tracker viewer)

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Core#82]
Apparently when I built those icons, I didn't include high-enough resolution for a nice crisp image in the toolbar on a high-dpi display like that on the Razer Blade 2014.

Need to:
- [ ] Find out which resolutions are needed in Windows icons these days
- [ ] Find out if we can commit the SVG versions of the logo and icons to this repo ( @yboger ?)
- [ ] Export the SVG at the correct resolutions
- [ ] Make an `.ICO` file with them - think IcoFX 1.6.4 (free) should work, though would be nice if there was something command-line and thus scriptable

Assigning to myself since I have the SVGs right now.

**Comment by feilen** [comment]
The most obvious way to generate PNG from SVG images would be through pretty much the only option most people use for SVG editing, the open source Inkscape program. To use export images with it:

```
inkscape -z -e icon.png -w WIDTH -h HEIGHT test.svg
```

If you have to combine these into a .ico file, imagemagick is good for the job:

```
convert icon-32.bmp icon-64.bmp icon-128.bmp icon-256.bmp myicon.ico
```

I believe imagemagick also supports PNG, but from what I've heard it's quite finicky and doesn't give as-good results.

**Comment by rpavlik** [comment]
Yes, made them in Inkscape, and that the inkscape command in a script is how I made them in the first place. Didn't realize imagemagick could make an `.ico`, though - I can't remember the command line tool I had used a few years back, but used IcoFX free (not command line) this past time.

I'm thinking it should be OK to commit the SVGs since there's lots of OSVR art out there now.

**Comment by rpavlik** [comment]
OK, looks like the stack is 16, 24, 32, 48, 256. Got the OK to commit. Not scripted right now, but better than before.
